
version: '2'
services:
  redis:
    image: redis
  db:
    image: mysql
    volumes:
      - /srv/transnat/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  transnat:
    image: lcasuol/transnational_system:latest
    #build: . 
    command: "bash -c 'ln -fs /srv/config/.env /var/www/html/transnat/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/transnat/storage:/var/www/transnat/storage
      - /srv/transnat/config:/srv/config
